### PR TITLE
Fix PHP 8.2 warnings

### PR DESCRIPTION
**Pull request by hemberger**
The only relevant breaking change in PHP 8.2 is that dynamic properties are deprecated. Since we're not intentionally using dynamic properties, the following changes are made:

* Make sure all class properties are declared.
* Fix a typo in property initialization (`allow_ampsersand` -> `allow_ampersand`).

These changes are needed for the tests to pass in PHP 8.2. ~~Unfortunately, the Circle-CI PHP 8.2 image isn't available yet, but I'll submit another PR adding it as soon as https://github.com/CircleCI-Public/cimg-php/pull/200 is merged.~~ The CircleCI test configuration for PHP 8.2. has been added!

### CODE REVIEW

**Comment by hemberger** [comment]
@tburry Would you be willing to review this PR? I'd like to start using PHP 8.2, and this is a blocking issue for me. Thank you!

**Comment by hemberger** [comment]
@charrondev Hi! I'm so sorry to bother you, but it seems like the previous maintainer of this package might not be active anymore. In that case, is there any chance that you or someone else at @vanilla would be able to help resolve this PR and release a new version? I helped to add support for PHP 8 last year, and am happy to continue maintaining compatibility with new PHP versions.

**Comment by charrondev** [comment]
Thanks for your contribution! The PR looks good to me, but unfortunately after the recent [CircleCI security incident](https://circleci.com/blog/jan-4-2023-incident-report/) we've disabled it everywhere. I'm currently passing through and replacing it with Github Actions.

If you don't mind I'll push a commit onto your branch with a new CI config, then merge it and tag a new release. I should be able to get this done today.

**Review by charrondev — APPROVED** [review]

**Comment by charrondev** [comment]
@hemberger New release for you here https://github.com/vanilla/nbbc/releases/tag/v2.4.0

**Comment by hemberger** [comment]
Thanks so much for your quick response! This is great!

**Comment by theyak** [comment]
@charrondev Making the properties protected may break things that use them outside of the code. Github wouldn't let me fork this to make a new PR or create an issue, so posting here in hopes someone sees it.

**Comment by hemberger** [comment]
Yep, that's a good point that I overlooked -- this did effectively change the visibility on these two properties (since the default when unspecified is public).

Out of curiosity, is this request only for theoretical backwards compatibility, or is there a use case for accessing these properties externally? They look like implementation details to me, but then again I'm not the original author. :)

**Comment by theyak** [comment]
We use it for checking quote depth (we prevent a quote depth greater than 3 levels deep) and estimating how long the content of the text is. It's also used for a couple of our custom tags.

**Comment by hemberger** [comment]
I see, my apologies for the bc break then! Would you like me to create a PR to change them to public? (It won't guarantee that any maintainers see it, but it may help it get resolved faster...)

**Comment by theyak** [comment]
Yes, please! Thanks for the swift response. We can work around it until it's merged.

**Comment by seanofw** [comment]
For what it's worth, I'm a little late to the party, but I'm not convinced this is a good idea.  The lexer and the stack really _should_ be private implementation details:  Exposing them to the outside world is possibly dangerous; mucking about with the stack especially could break a lot of stuff.

If checking/limiting depth for certain kinds of tags is a desired use case, that should probably be first-class functionality (a `NestingLimit` property perhaps), so that you don't have to mess around with internals to get the desired behavior.  Same for estimating the size of the text (which isn't really all that reliable, but I'm sure you have your reasons why you're doing it).

Of course, these properties likely have been public for a long time now, so hiding them again might be a breaking change, but they were never intended to be public when I first wrote this all those years ago 😅

**Pull request merged**
